// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: first_grpc_project.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_first_5fgrpc_5fproject_2eproto__INCLUDED
#define GRPC_first_5fgrpc_5fproject_2eproto__INCLUDED

#include "first_grpc_project.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace first_grpc_project {

// The greeting service definition.
//
class Adder final {
 public:
  static constexpr char const* service_full_name() {
    return "first_grpc_project.Adder";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends an addRequest
    virtual ::grpc::Status add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::first_grpc_project::addResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::first_grpc_project::addResponse>> Asyncadd(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::first_grpc_project::addResponse>>(AsyncaddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::first_grpc_project::addResponse>> PrepareAsyncadd(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::first_grpc_project::addResponse>>(PrepareAsyncaddRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends an addRequest
      virtual void add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::first_grpc_project::addResponse>* AsyncaddRaw(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::first_grpc_project::addResponse>* PrepareAsyncaddRaw(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::first_grpc_project::addResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>> Asyncadd(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>>(AsyncaddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>> PrepareAsyncadd(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>>(PrepareAsyncaddRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response, std::function<void(::grpc::Status)>) override;
      void add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>* AsyncaddRaw(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>* PrepareAsyncaddRaw(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_add_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends an addRequest
    virtual ::grpc::Status add(::grpc::ServerContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_add() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add(::grpc::ServerContext* /*context*/, const ::first_grpc_project::addRequest* /*request*/, ::first_grpc_project::addResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd(::grpc::ServerContext* context, ::first_grpc_project::addRequest* request, ::grpc::ServerAsyncResponseWriter< ::first_grpc_project::addResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_add<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_add() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::first_grpc_project::addRequest, ::first_grpc_project::addResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response) { return this->add(context, request, response); }));}
    void SetMessageAllocatorFor_add(
        ::grpc::MessageAllocator< ::first_grpc_project::addRequest, ::first_grpc_project::addResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::first_grpc_project::addRequest, ::first_grpc_project::addResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add(::grpc::ServerContext* /*context*/, const ::first_grpc_project::addRequest* /*request*/, ::first_grpc_project::addResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add(
      ::grpc::CallbackServerContext* /*context*/, const ::first_grpc_project::addRequest* /*request*/, ::first_grpc_project::addResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_add<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_add() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add(::grpc::ServerContext* /*context*/, const ::first_grpc_project::addRequest* /*request*/, ::first_grpc_project::addResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_add() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add(::grpc::ServerContext* /*context*/, const ::first_grpc_project::addRequest* /*request*/, ::first_grpc_project::addResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestadd(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_add() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->add(context, request, response); }));
    }
    ~WithRawCallbackMethod_add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status add(::grpc::ServerContext* /*context*/, const ::first_grpc_project::addRequest* /*request*/, ::first_grpc_project::addResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* add(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_add() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::first_grpc_project::addRequest, ::first_grpc_project::addResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::first_grpc_project::addRequest, ::first_grpc_project::addResponse>* streamer) {
                       return this->Streamedadd(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status add(::grpc::ServerContext* /*context*/, const ::first_grpc_project::addRequest* /*request*/, ::first_grpc_project::addResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedadd(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::first_grpc_project::addRequest,::first_grpc_project::addResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_add<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_add<Service > StreamedService;
};

}  // namespace first_grpc_project


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_first_5fgrpc_5fproject_2eproto__INCLUDED
