// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: first_grpc_project.proto
// Protobuf C++ Version: 6.30.0

#ifndef first_5fgrpc_5fproject_2eproto_2epb_2eh
#define first_5fgrpc_5fproject_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_first_5fgrpc_5fproject_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_first_5fgrpc_5fproject_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_first_5fgrpc_5fproject_2eproto;
}  // extern "C"
namespace first_grpc_project {
class addRequest;
struct addRequestDefaultTypeInternal;
extern addRequestDefaultTypeInternal _addRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull addRequest_class_data_;
class addResponse;
struct addResponseDefaultTypeInternal;
extern addResponseDefaultTypeInternal _addResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull addResponse_class_data_;
}  // namespace first_grpc_project
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace first_grpc_project {

// ===================================================================


// -------------------------------------------------------------------

class addResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:first_grpc_project.addResponse) */ {
 public:
  inline addResponse() : addResponse(nullptr) {}
  ~addResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(addResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(addResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR addResponse(::google::protobuf::internal::ConstantInitialized);

  inline addResponse(const addResponse& from) : addResponse(nullptr, from) {}
  inline addResponse(addResponse&& from) noexcept
      : addResponse(nullptr, std::move(from)) {}
  inline addResponse& operator=(const addResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline addResponse& operator=(addResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const addResponse& default_instance() {
    return *reinterpret_cast<const addResponse*>(
        &_addResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(addResponse& a, addResponse& b) { a.Swap(&b); }
  inline void Swap(addResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(addResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  addResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<addResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const addResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const addResponse& from) { addResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(addResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "first_grpc_project.addResponse"; }

 protected:
  explicit addResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  addResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const addResponse& from);
  addResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, addResponse&& from) noexcept
      : addResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultFieldNumber = 1,
  };
  // int32 result = 1;
  void clear_result() ;
  ::int32_t result() const;
  void set_result(::int32_t value);

  private:
  ::int32_t _internal_result() const;
  void _internal_set_result(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:first_grpc_project.addResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const addResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t result_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_first_5fgrpc_5fproject_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull addResponse_class_data_;
// -------------------------------------------------------------------

class addRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:first_grpc_project.addRequest) */ {
 public:
  inline addRequest() : addRequest(nullptr) {}
  ~addRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(addRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(addRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR addRequest(::google::protobuf::internal::ConstantInitialized);

  inline addRequest(const addRequest& from) : addRequest(nullptr, from) {}
  inline addRequest(addRequest&& from) noexcept
      : addRequest(nullptr, std::move(from)) {}
  inline addRequest& operator=(const addRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline addRequest& operator=(addRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const addRequest& default_instance() {
    return *reinterpret_cast<const addRequest*>(
        &_addRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(addRequest& a, addRequest& b) { a.Swap(&b); }
  inline void Swap(addRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(addRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  addRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<addRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const addRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const addRequest& from) { addRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(addRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "first_grpc_project.addRequest"; }

 protected:
  explicit addRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  addRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const addRequest& from);
  addRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, addRequest&& from) noexcept
      : addRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNum1FieldNumber = 1,
    kNum2FieldNumber = 2,
  };
  // int32 num1 = 1;
  void clear_num1() ;
  ::int32_t num1() const;
  void set_num1(::int32_t value);

  private:
  ::int32_t _internal_num1() const;
  void _internal_set_num1(::int32_t value);

  public:
  // int32 num2 = 2;
  void clear_num2() ;
  ::int32_t num2() const;
  void set_num2(::int32_t value);

  private:
  ::int32_t _internal_num2() const;
  void _internal_set_num2(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:first_grpc_project.addRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const addRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t num1_;
    ::int32_t num2_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_first_5fgrpc_5fproject_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull addRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// addRequest

// int32 num1 = 1;
inline void addRequest::clear_num1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t addRequest::num1() const {
  // @@protoc_insertion_point(field_get:first_grpc_project.addRequest.num1)
  return _internal_num1();
}
inline void addRequest::set_num1(::int32_t value) {
  _internal_set_num1(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:first_grpc_project.addRequest.num1)
}
inline ::int32_t addRequest::_internal_num1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num1_;
}
inline void addRequest::_internal_set_num1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num1_ = value;
}

// int32 num2 = 2;
inline void addRequest::clear_num2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num2_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t addRequest::num2() const {
  // @@protoc_insertion_point(field_get:first_grpc_project.addRequest.num2)
  return _internal_num2();
}
inline void addRequest::set_num2(::int32_t value) {
  _internal_set_num2(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:first_grpc_project.addRequest.num2)
}
inline ::int32_t addRequest::_internal_num2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num2_;
}
inline void addRequest::_internal_set_num2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num2_ = value;
}

// -------------------------------------------------------------------

// addResponse

// int32 result = 1;
inline void addResponse::clear_result() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t addResponse::result() const {
  // @@protoc_insertion_point(field_get:first_grpc_project.addResponse.result)
  return _internal_result();
}
inline void addResponse::set_result(::int32_t value) {
  _internal_set_result(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:first_grpc_project.addResponse.result)
}
inline ::int32_t addResponse::_internal_result() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_;
}
inline void addResponse::_internal_set_result(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace first_grpc_project


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // first_5fgrpc_5fproject_2eproto_2epb_2eh
