// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: first_grpc_project.proto

#include "first_grpc_project.pb.h"
#include "first_grpc_project.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace first_grpc_project {

static const char* Adder_method_names[] = {
  "/first_grpc_project.Adder/add",
};

std::unique_ptr< Adder::Stub> Adder::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Adder::Stub> stub(new Adder::Stub(channel, options));
  return stub;
}

Adder::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_add_(Adder_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Adder::Stub::add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::first_grpc_project::addResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::first_grpc_project::addRequest, ::first_grpc_project::addResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_add_, context, request, response);
}

void Adder::Stub::async::add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::first_grpc_project::addRequest, ::first_grpc_project::addResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_, context, request, response, std::move(f));
}

void Adder::Stub::async::add(::grpc::ClientContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>* Adder::Stub::PrepareAsyncaddRaw(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::first_grpc_project::addResponse, ::first_grpc_project::addRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_add_, context, request);
}

::grpc::ClientAsyncResponseReader< ::first_grpc_project::addResponse>* Adder::Stub::AsyncaddRaw(::grpc::ClientContext* context, const ::first_grpc_project::addRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddRaw(context, request, cq);
  result->StartCall();
  return result;
}

Adder::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Adder_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Adder::Service, ::first_grpc_project::addRequest, ::first_grpc_project::addResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Adder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::first_grpc_project::addRequest* req,
             ::first_grpc_project::addResponse* resp) {
               return service->add(ctx, req, resp);
             }, this)));
}

Adder::Service::~Service() {
}

::grpc::Status Adder::Service::add(::grpc::ServerContext* context, const ::first_grpc_project::addRequest* request, ::first_grpc_project::addResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace first_grpc_project

