// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: first_grpc_project.proto
// Protobuf C++ Version: 6.30.0

#include "first_grpc_project.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace first_grpc_project {

inline constexpr tableResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        num_{0},
        n_{0},
        result_{0} {}

template <typename>
PROTOBUF_CONSTEXPR tableResponse::tableResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(tableResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct tableResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR tableResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~tableResponseDefaultTypeInternal() {}
  union {
    tableResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 tableResponseDefaultTypeInternal _tableResponse_default_instance_;

inline constexpr tableRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        num_{0},
        n_{0} {}

template <typename>
PROTOBUF_CONSTEXPR tableRequest::tableRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(tableRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct tableRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR tableRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~tableRequestDefaultTypeInternal() {}
  union {
    tableRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 tableRequestDefaultTypeInternal _tableRequest_default_instance_;

inline constexpr addResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        result_{0} {}

template <typename>
PROTOBUF_CONSTEXPR addResponse::addResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(addResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct addResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR addResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~addResponseDefaultTypeInternal() {}
  union {
    addResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 addResponseDefaultTypeInternal _addResponse_default_instance_;

inline constexpr addRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        num1_{0},
        num2_{0} {}

template <typename>
PROTOBUF_CONSTEXPR addRequest::addRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(addRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct addRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR addRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~addRequestDefaultTypeInternal() {}
  union {
    addRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 addRequestDefaultTypeInternal _addRequest_default_instance_;
}  // namespace first_grpc_project
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_first_5fgrpc_5fproject_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_first_5fgrpc_5fproject_2eproto = nullptr;
const ::uint32_t
    TableStruct_first_5fgrpc_5fproject_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::addRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::addRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::addRequest, _impl_.num1_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::addRequest, _impl_.num2_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::addResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::addResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::addResponse, _impl_.result_),
        0,
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableRequest, _impl_.num_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableRequest, _impl_.n_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableResponse, _impl_.num_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableResponse, _impl_.n_),
        PROTOBUF_FIELD_OFFSET(::first_grpc_project::tableResponse, _impl_.result_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::first_grpc_project::addRequest)},
        {12, 21, -1, sizeof(::first_grpc_project::addResponse)},
        {22, 32, -1, sizeof(::first_grpc_project::tableRequest)},
        {34, 45, -1, sizeof(::first_grpc_project::tableResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::first_grpc_project::_addRequest_default_instance_._instance,
    &::first_grpc_project::_addResponse_default_instance_._instance,
    &::first_grpc_project::_tableRequest_default_instance_._instance,
    &::first_grpc_project::_tableResponse_default_instance_._instance,
};
const char descriptor_table_protodef_first_5fgrpc_5fproject_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030first_grpc_project.proto\022\022first_grpc_p"
    "roject\"(\n\naddRequest\022\014\n\004num1\030\001 \001(\005\022\014\n\004nu"
    "m2\030\002 \001(\005\"\035\n\013addResponse\022\016\n\006result\030\001 \001(\005\""
    "&\n\014tableRequest\022\013\n\003num\030\001 \001(\005\022\t\n\001n\030\002 \001(\005\""
    "7\n\rtableResponse\022\013\n\003num\030\001 \001(\005\022\t\n\001n\030\002 \001(\005"
    "\022\016\n\006result\030\003 \001(\0052\264\001\n\005Adder\022H\n\003add\022\036.firs"
    "t_grpc_project.addRequest\032\037.first_grpc_p"
    "roject.addResponse\"\000\022a\n\026getMultiplicatio"
    "nTable\022 .first_grpc_project.tableRequest"
    "\032!.first_grpc_project.tableResponse\"\0000\001B"
    ";\n\032io.grpc.first_grpc_projectB\025FirstGrpc"
    "ProjectProtoP\001\242\002\003HLWb\006proto3"
};
static ::absl::once_flag descriptor_table_first_5fgrpc_5fproject_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_first_5fgrpc_5fproject_2eproto = {
    false,
    false,
    468,
    descriptor_table_protodef_first_5fgrpc_5fproject_2eproto,
    "first_grpc_project.proto",
    &descriptor_table_first_5fgrpc_5fproject_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_first_5fgrpc_5fproject_2eproto::offsets,
    file_level_enum_descriptors_first_5fgrpc_5fproject_2eproto,
    file_level_service_descriptors_first_5fgrpc_5fproject_2eproto,
};
namespace first_grpc_project {
// ===================================================================

class addRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<addRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(addRequest, _impl_._has_bits_);
};

addRequest::addRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, addRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:first_grpc_project.addRequest)
}
addRequest::addRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const addRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, addRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE addRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void addRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num1_),
           0,
           offsetof(Impl_, num2_) -
               offsetof(Impl_, num1_) +
               sizeof(Impl_::num2_));
}
addRequest::~addRequest() {
  // @@protoc_insertion_point(destructor:first_grpc_project.addRequest)
  SharedDtor(*this);
}
inline void addRequest::SharedDtor(MessageLite& self) {
  addRequest& this_ = static_cast<addRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL addRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) addRequest(arena);
}
constexpr auto addRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(addRequest),
                                            alignof(addRequest));
}
constexpr auto addRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_addRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &addRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<addRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &addRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<addRequest>(), &addRequest::ByteSizeLong,
              &addRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(addRequest, _impl_._cached_size_),
          false,
      },
      &addRequest::kDescriptorMethods,
      &descriptor_table_first_5fgrpc_5fproject_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        addRequest_class_data_ =
            addRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL addRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&addRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(addRequest_class_data_.tc_table);
  return addRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
addRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(addRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    addRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::first_grpc_project::addRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 num2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(addRequest, _impl_.num2_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(addRequest, _impl_.num2_)}},
    // int32 num1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(addRequest, _impl_.num1_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(addRequest, _impl_.num1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 num1 = 1;
    {PROTOBUF_FIELD_OFFSET(addRequest, _impl_.num1_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 num2 = 2;
    {PROTOBUF_FIELD_OFFSET(addRequest, _impl_.num2_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void addRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:first_grpc_project.addRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.num1_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.num2_) -
        reinterpret_cast<char*>(&_impl_.num1_)) + sizeof(_impl_.num2_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL addRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const addRequest& this_ = static_cast<const addRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL addRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const addRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:first_grpc_project.addRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 num1 = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_num1() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_num1(), target);
    }
  }

  // int32 num2 = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_num2() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_num2(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:first_grpc_project.addRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t addRequest::ByteSizeLong(const MessageLite& base) {
  const addRequest& this_ = static_cast<const addRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t addRequest::ByteSizeLong() const {
  const addRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:first_grpc_project.addRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // int32 num1 = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_num1() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_num1());
      }
    }
    // int32 num2 = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_num2() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_num2());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void addRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<addRequest*>(&to_msg);
  auto& from = static_cast<const addRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:first_grpc_project.addRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_num1() != 0) {
        _this->_impl_.num1_ = from._impl_.num1_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_num2() != 0) {
        _this->_impl_.num2_ = from._impl_.num2_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void addRequest::CopyFrom(const addRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:first_grpc_project.addRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void addRequest::InternalSwap(addRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(addRequest, _impl_.num2_)
      + sizeof(addRequest::_impl_.num2_)
      - PROTOBUF_FIELD_OFFSET(addRequest, _impl_.num1_)>(
          reinterpret_cast<char*>(&_impl_.num1_),
          reinterpret_cast<char*>(&other->_impl_.num1_));
}

::google::protobuf::Metadata addRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class addResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<addResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(addResponse, _impl_._has_bits_);
};

addResponse::addResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, addResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:first_grpc_project.addResponse)
}
addResponse::addResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const addResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, addResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE addResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void addResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
addResponse::~addResponse() {
  // @@protoc_insertion_point(destructor:first_grpc_project.addResponse)
  SharedDtor(*this);
}
inline void addResponse::SharedDtor(MessageLite& self) {
  addResponse& this_ = static_cast<addResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL addResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) addResponse(arena);
}
constexpr auto addResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(addResponse),
                                            alignof(addResponse));
}
constexpr auto addResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_addResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &addResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<addResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &addResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<addResponse>(), &addResponse::ByteSizeLong,
              &addResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(addResponse, _impl_._cached_size_),
          false,
      },
      &addResponse::kDescriptorMethods,
      &descriptor_table_first_5fgrpc_5fproject_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        addResponse_class_data_ =
            addResponse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL addResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&addResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(addResponse_class_data_.tc_table);
  return addResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
addResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(addResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    addResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::first_grpc_project::addResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(addResponse, _impl_.result_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(addResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 result = 1;
    {PROTOBUF_FIELD_OFFSET(addResponse, _impl_.result_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void addResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:first_grpc_project.addResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL addResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const addResponse& this_ = static_cast<const addResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL addResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const addResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:first_grpc_project.addResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 result = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_result() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_result(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:first_grpc_project.addResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t addResponse::ByteSizeLong(const MessageLite& base) {
  const addResponse& this_ = static_cast<const addResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t addResponse::ByteSizeLong() const {
  const addResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:first_grpc_project.addResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 result = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_result() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_result());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void addResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<addResponse*>(&to_msg);
  auto& from = static_cast<const addResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:first_grpc_project.addResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_result() != 0) {
      _this->_impl_.result_ = from._impl_.result_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void addResponse::CopyFrom(const addResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:first_grpc_project.addResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void addResponse::InternalSwap(addResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata addResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class tableRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<tableRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(tableRequest, _impl_._has_bits_);
};

tableRequest::tableRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, tableRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:first_grpc_project.tableRequest)
}
tableRequest::tableRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const tableRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, tableRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE tableRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void tableRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num_),
           0,
           offsetof(Impl_, n_) -
               offsetof(Impl_, num_) +
               sizeof(Impl_::n_));
}
tableRequest::~tableRequest() {
  // @@protoc_insertion_point(destructor:first_grpc_project.tableRequest)
  SharedDtor(*this);
}
inline void tableRequest::SharedDtor(MessageLite& self) {
  tableRequest& this_ = static_cast<tableRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL tableRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) tableRequest(arena);
}
constexpr auto tableRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(tableRequest),
                                            alignof(tableRequest));
}
constexpr auto tableRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_tableRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &tableRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<tableRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &tableRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<tableRequest>(), &tableRequest::ByteSizeLong,
              &tableRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(tableRequest, _impl_._cached_size_),
          false,
      },
      &tableRequest::kDescriptorMethods,
      &descriptor_table_first_5fgrpc_5fproject_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        tableRequest_class_data_ =
            tableRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL tableRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&tableRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(tableRequest_class_data_.tc_table);
  return tableRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
tableRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(tableRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    tableRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::first_grpc_project::tableRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 n = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(tableRequest, _impl_.n_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(tableRequest, _impl_.n_)}},
    // int32 num = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(tableRequest, _impl_.num_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(tableRequest, _impl_.num_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 num = 1;
    {PROTOBUF_FIELD_OFFSET(tableRequest, _impl_.num_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 n = 2;
    {PROTOBUF_FIELD_OFFSET(tableRequest, _impl_.n_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void tableRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:first_grpc_project.tableRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.num_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.n_) -
        reinterpret_cast<char*>(&_impl_.num_)) + sizeof(_impl_.n_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL tableRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const tableRequest& this_ = static_cast<const tableRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL tableRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const tableRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:first_grpc_project.tableRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 num = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_num() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_num(), target);
    }
  }

  // int32 n = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_n() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_n(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:first_grpc_project.tableRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t tableRequest::ByteSizeLong(const MessageLite& base) {
  const tableRequest& this_ = static_cast<const tableRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t tableRequest::ByteSizeLong() const {
  const tableRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:first_grpc_project.tableRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // int32 num = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_num() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_num());
      }
    }
    // int32 n = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_n() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_n());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void tableRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<tableRequest*>(&to_msg);
  auto& from = static_cast<const tableRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:first_grpc_project.tableRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_num() != 0) {
        _this->_impl_.num_ = from._impl_.num_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_n() != 0) {
        _this->_impl_.n_ = from._impl_.n_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void tableRequest::CopyFrom(const tableRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:first_grpc_project.tableRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void tableRequest::InternalSwap(tableRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(tableRequest, _impl_.n_)
      + sizeof(tableRequest::_impl_.n_)
      - PROTOBUF_FIELD_OFFSET(tableRequest, _impl_.num_)>(
          reinterpret_cast<char*>(&_impl_.num_),
          reinterpret_cast<char*>(&other->_impl_.num_));
}

::google::protobuf::Metadata tableRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class tableResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<tableResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(tableResponse, _impl_._has_bits_);
};

tableResponse::tableResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, tableResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:first_grpc_project.tableResponse)
}
tableResponse::tableResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const tableResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, tableResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE tableResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void tableResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, num_),
           0,
           offsetof(Impl_, result_) -
               offsetof(Impl_, num_) +
               sizeof(Impl_::result_));
}
tableResponse::~tableResponse() {
  // @@protoc_insertion_point(destructor:first_grpc_project.tableResponse)
  SharedDtor(*this);
}
inline void tableResponse::SharedDtor(MessageLite& self) {
  tableResponse& this_ = static_cast<tableResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL tableResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) tableResponse(arena);
}
constexpr auto tableResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(tableResponse),
                                            alignof(tableResponse));
}
constexpr auto tableResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_tableResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &tableResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<tableResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &tableResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<tableResponse>(), &tableResponse::ByteSizeLong,
              &tableResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(tableResponse, _impl_._cached_size_),
          false,
      },
      &tableResponse::kDescriptorMethods,
      &descriptor_table_first_5fgrpc_5fproject_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        tableResponse_class_data_ =
            tableResponse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL tableResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&tableResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(tableResponse_class_data_.tc_table);
  return tableResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
tableResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(tableResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    tableResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::first_grpc_project::tableResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 num = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(tableResponse, _impl_.num_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.num_)}},
    // int32 n = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(tableResponse, _impl_.n_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.n_)}},
    // int32 result = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(tableResponse, _impl_.result_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 num = 1;
    {PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.num_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 n = 2;
    {PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.n_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 result = 3;
    {PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.result_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void tableResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:first_grpc_project.tableResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.num_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.result_) -
        reinterpret_cast<char*>(&_impl_.num_)) + sizeof(_impl_.result_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL tableResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const tableResponse& this_ = static_cast<const tableResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL tableResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const tableResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:first_grpc_project.tableResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 num = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_num() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_num(), target);
    }
  }

  // int32 n = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_n() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_n(), target);
    }
  }

  // int32 result = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_result() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_result(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:first_grpc_project.tableResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t tableResponse::ByteSizeLong(const MessageLite& base) {
  const tableResponse& this_ = static_cast<const tableResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t tableResponse::ByteSizeLong() const {
  const tableResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:first_grpc_project.tableResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // int32 num = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_num() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_num());
      }
    }
    // int32 n = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_n() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_n());
      }
    }
    // int32 result = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_result() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_result());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void tableResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<tableResponse*>(&to_msg);
  auto& from = static_cast<const tableResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:first_grpc_project.tableResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_num() != 0) {
        _this->_impl_.num_ = from._impl_.num_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_n() != 0) {
        _this->_impl_.n_ = from._impl_.n_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_result() != 0) {
        _this->_impl_.result_ = from._impl_.result_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void tableResponse::CopyFrom(const tableResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:first_grpc_project.tableResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void tableResponse::InternalSwap(tableResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.result_)
      + sizeof(tableResponse::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(tableResponse, _impl_.num_)>(
          reinterpret_cast<char*>(&_impl_.num_),
          reinterpret_cast<char*>(&other->_impl_.num_));
}

::google::protobuf::Metadata tableResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace first_grpc_project
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_first_5fgrpc_5fproject_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
